language: python

python:
  - "2.7"

env:
  # - TEST=py-without-modules
  # - TEST=py-select-gc
  # - TEST=py-pool
  # - TEST=py-epool
  - TEST=py-glib2
  # - TEST=pyflakes
  # - TEST=api-reference
  # - TEST=documentation

matrix:
  include:
    - python: "3.3"
      env: TEST=python-3.3-tests

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

# command to run tests
script:
  - ./bin/admin/travis-test $TEST
