language: python

python:
  - "2.7"

env:
  - TEST=py-without-modules
  - TEST=py-select-gc
  - TEST=py-pool
  - TEST=py-epool
  - TEST=py-glib2


matrix:
  include:
    - python: "3.3"
      env: TEST=py-3.3
    - python: "2.7"
      env: TEST=pyflakes
    - python: "2.7"
      env: TEST=api-reference
    - python: "2.7"
      env: TEST=documentation

# Each builder has its own install requirements in order
# to avoid installing unused packages.
install:
  - echo "Custom install steps for each builder."

# command to run tests
script:
  - ./bin/admin/travis-test $TEST
