#
# Travis CI configuration file for Twisted tests.
#
language: python

# python:
#   - "2.7"

# Tests on supported Python version are executed with various reactors.
# env:
#   - TEST=py-select
#   - TEST=py-poll
#   - TEST=py-epoll

after_failure: "cat _trial_temp/test.log"


# In addition, some tests are executed on a single Python version.
matrix:
  include:
    # Python 3.3 tests are only executed once while Twisted is in migration
    # process.
    # - python: "3.3"
    #   env: TEST=py-3.3
    # - python: "2.7"
    #   env: TEST=py-without-modules
    - python: "2.7"
      env: TEST=py-glib2
    # - python: "2.7"
    #   env: TEST=py-gi
    # - python: "2.7"
    #   env: TEST=py-gtk2
    # - python: "2.7"
    #   env: TEST=py-gtk3
    # - python: "2.7"
    #   env: TEST=pyflakes
    # - python: "2.7"
    #   env: TEST=api-reference
    # - python: "2.7"
    #   env: TEST=documentation

# Each builder has its own install requirements in order
# to avoid installing unused packages.
install:
  - echo "Custom install steps for each builder."

# Command used for executing the tests, where $TEST is extracted from `env`.
script:
  - ./bin/admin/travis-test $TEST
